package cn.edu.bupt.lab805.pestguide.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import cn.edu.bupt.lab805.pestguide.entity.Action;
import cn.edu.bupt.lab805.pestguide.entity.City;
import cn.edu.bupt.lab805.pestguide.entity.Depot;
import cn.edu.bupt.lab805.pestguide.entity.Factory;
import cn.edu.bupt.lab805.pestguide.entity.Grain;
import cn.edu.bupt.lab805.pestguide.entity.Logininfo;
import cn.edu.bupt.lab805.pestguide.entity.Pest;
import cn.edu.bupt.lab805.pestguide.entity.TRealInsects;
import cn.edu.bupt.lab805.pestguide.entity.Upload;
import cn.edu.bupt.lab805.pestguide.entity.User;

import cn.edu.bupt.lab805.pestguide.dao.ActionDao;
import cn.edu.bupt.lab805.pestguide.dao.CityDao;
import cn.edu.bupt.lab805.pestguide.dao.DepotDao;
import cn.edu.bupt.lab805.pestguide.dao.FactoryDao;
import cn.edu.bupt.lab805.pestguide.dao.GrainDao;
import cn.edu.bupt.lab805.pestguide.dao.LogininfoDao;
import cn.edu.bupt.lab805.pestguide.dao.PestDao;
import cn.edu.bupt.lab805.pestguide.dao.TRealInsectsDao;
import cn.edu.bupt.lab805.pestguide.dao.UploadDao;
import cn.edu.bupt.lab805.pestguide.dao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig actionDaoConfig;
    private final DaoConfig cityDaoConfig;
    private final DaoConfig depotDaoConfig;
    private final DaoConfig factoryDaoConfig;
    private final DaoConfig grainDaoConfig;
    private final DaoConfig logininfoDaoConfig;
    private final DaoConfig pestDaoConfig;
    private final DaoConfig tRealInsectsDaoConfig;
    private final DaoConfig uploadDaoConfig;
    private final DaoConfig userDaoConfig;

    private final ActionDao actionDao;
    private final CityDao cityDao;
    private final DepotDao depotDao;
    private final FactoryDao factoryDao;
    private final GrainDao grainDao;
    private final LogininfoDao logininfoDao;
    private final PestDao pestDao;
    private final TRealInsectsDao tRealInsectsDao;
    private final UploadDao uploadDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        actionDaoConfig = daoConfigMap.get(ActionDao.class).clone();
        actionDaoConfig.initIdentityScope(type);

        cityDaoConfig = daoConfigMap.get(CityDao.class).clone();
        cityDaoConfig.initIdentityScope(type);

        depotDaoConfig = daoConfigMap.get(DepotDao.class).clone();
        depotDaoConfig.initIdentityScope(type);

        factoryDaoConfig = daoConfigMap.get(FactoryDao.class).clone();
        factoryDaoConfig.initIdentityScope(type);

        grainDaoConfig = daoConfigMap.get(GrainDao.class).clone();
        grainDaoConfig.initIdentityScope(type);

        logininfoDaoConfig = daoConfigMap.get(LogininfoDao.class).clone();
        logininfoDaoConfig.initIdentityScope(type);

        pestDaoConfig = daoConfigMap.get(PestDao.class).clone();
        pestDaoConfig.initIdentityScope(type);

        tRealInsectsDaoConfig = daoConfigMap.get(TRealInsectsDao.class).clone();
        tRealInsectsDaoConfig.initIdentityScope(type);

        uploadDaoConfig = daoConfigMap.get(UploadDao.class).clone();
        uploadDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        actionDao = new ActionDao(actionDaoConfig, this);
        cityDao = new CityDao(cityDaoConfig, this);
        depotDao = new DepotDao(depotDaoConfig, this);
        factoryDao = new FactoryDao(factoryDaoConfig, this);
        grainDao = new GrainDao(grainDaoConfig, this);
        logininfoDao = new LogininfoDao(logininfoDaoConfig, this);
        pestDao = new PestDao(pestDaoConfig, this);
        tRealInsectsDao = new TRealInsectsDao(tRealInsectsDaoConfig, this);
        uploadDao = new UploadDao(uploadDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Action.class, actionDao);
        registerDao(City.class, cityDao);
        registerDao(Depot.class, depotDao);
        registerDao(Factory.class, factoryDao);
        registerDao(Grain.class, grainDao);
        registerDao(Logininfo.class, logininfoDao);
        registerDao(Pest.class, pestDao);
        registerDao(TRealInsects.class, tRealInsectsDao);
        registerDao(Upload.class, uploadDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        actionDaoConfig.clearIdentityScope();
        cityDaoConfig.clearIdentityScope();
        depotDaoConfig.clearIdentityScope();
        factoryDaoConfig.clearIdentityScope();
        grainDaoConfig.clearIdentityScope();
        logininfoDaoConfig.clearIdentityScope();
        pestDaoConfig.clearIdentityScope();
        tRealInsectsDaoConfig.clearIdentityScope();
        uploadDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public ActionDao getActionDao() {
        return actionDao;
    }

    public CityDao getCityDao() {
        return cityDao;
    }

    public DepotDao getDepotDao() {
        return depotDao;
    }

    public FactoryDao getFactoryDao() {
        return factoryDao;
    }

    public GrainDao getGrainDao() {
        return grainDao;
    }

    public LogininfoDao getLogininfoDao() {
        return logininfoDao;
    }

    public PestDao getPestDao() {
        return pestDao;
    }

    public TRealInsectsDao getTRealInsectsDao() {
        return tRealInsectsDao;
    }

    public UploadDao getUploadDao() {
        return uploadDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
