package cn.edu.bupt.lab805.pestguide.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import cn.edu.bupt.lab805.pestguide.entity.TRealInsects;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TREAL_INSECTS".
*/
public class TRealInsectsDao extends AbstractDao<TRealInsects, Long> {

    public static final String TABLENAME = "TREAL_INSECTS";

    /**
     * Properties of entity TRealInsects.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Kind = new Property(1, String.class, "kind", false, "KIND");
        public final static Property Stage = new Property(2, String.class, "stage", false, "STAGE");
        public final static Property Num = new Property(3, Integer.class, "num", false, "NUM");
        public final static Property Pid = new Property(4, Long.class, "pid", false, "PID");
    }


    public TRealInsectsDao(DaoConfig config) {
        super(config);
    }
    
    public TRealInsectsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TREAL_INSECTS\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"KIND\" TEXT," + // 1: kind
                "\"STAGE\" TEXT," + // 2: stage
                "\"NUM\" INTEGER," + // 3: num
                "\"PID\" INTEGER);"); // 4: pid
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TREAL_INSECTS\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TRealInsects entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String kind = entity.getKind();
        if (kind != null) {
            stmt.bindString(2, kind);
        }
 
        String stage = entity.getStage();
        if (stage != null) {
            stmt.bindString(3, stage);
        }
 
        Integer num = entity.getNum();
        if (num != null) {
            stmt.bindLong(4, num);
        }
 
        Long pid = entity.getPid();
        if (pid != null) {
            stmt.bindLong(5, pid);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TRealInsects entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String kind = entity.getKind();
        if (kind != null) {
            stmt.bindString(2, kind);
        }
 
        String stage = entity.getStage();
        if (stage != null) {
            stmt.bindString(3, stage);
        }
 
        Integer num = entity.getNum();
        if (num != null) {
            stmt.bindLong(4, num);
        }
 
        Long pid = entity.getPid();
        if (pid != null) {
            stmt.bindLong(5, pid);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public TRealInsects readEntity(Cursor cursor, int offset) {
        TRealInsects entity = new TRealInsects( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // kind
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // stage
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // num
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4) // pid
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TRealInsects entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setKind(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setStage(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setNum(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setPid(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(TRealInsects entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(TRealInsects entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(TRealInsects entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
